---
title: "DS311 Q6"
author: "Gabrielle Salamanca"
date: "April 13, 2023"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## We-R-Finished

### Q6 EDA

1. Reading the data into R

```{r}
library(readr)
library(dplyr)
# dataset
COL <- read_csv("./CostOfLiving2023.csv", show_col_types = FALSE)
coldf <- COL[, !(names(COL) %in% c("fips"))]
head(coldf)
```

2. Making columns into variables

```{r}
state <- coldf$state
density <- coldf$densityMi
pop2023 <- coldf$pop2023
pop2022 <- coldf$pop2022
pop2020 <- coldf$pop2019
pop2019 <- coldf$pop2019
pop2010 <- coldf$pop2010
growthRate <- coldf$growthRate
growth <- coldf$growth
growth2010 <- coldf$growthSince2010
costIndex <- coldf$costIndex
grocery <- coldf$groceryCost
housing <- coldf$housingCost
utility <- coldf$utilitiesCost
transport <- coldf$transportationCost
misc <- coldf$miscCost
```

3. Top 10 states

```{r}
top10 <- c("Texas", "New York", "New Jersey", "Illinois", 
           "Massachusetts", "Virginia", "Pennsylvania", 
           "Washington", "Michigan", "North Carolina")
# filter
live <- coldf[, -2:-10]
live <- live[order(live$state), decreasing = TRUE,]
top <- live[c(13, 21, 22, 30, 32, 33, 38, 43, 46, 47),]
top
```

4. Cost Index testing

```{r}
n <- 5
# Illinois
IL <- 98.4 + 86.6 + 96.5 + 105.8 + 96.7
ILcost <- IL/n
trueIL <- 94.3
cat("The average index in Illinois is", ILcost, ", and the cost index is", trueIL, "\n")

# Massachusetts
MA <- 119.3 + 177.6 + 111.1 + 111.3 + 116.1
MAcost <- MA/n
trueMA <- 135.0
cat("The average index in Massachusetts is", MAcost, ", and the cost index is", trueMA, "\n")

# Michigan
MI <- 90.1 + 80.7 + 99.7 + 103.2 + 96.4
MIcost <- MI/n
trueMI <- 91.3
cat("The average index in Michigan is", MIcost, ", and the cost index is", trueMI, "\n")

# New Jersey
NJ <- 107.3 + 136.6 + 104.6 + 105.5 + 106.6
NJcost <- NJ/n
trueNJ <- 115.2
cat("The average index in New Jersey is", ILcost, ", and the cost index is", trueIL, "\n")

# New York
NY <- 118.4 + 230.1 + 99.8 + 108.7 + 114.8
NYcost <- NY/n
trueNY <- 148.2
cat("The average index in New York is", NYcost, ", and the cost index is", trueNY, "\n")

# North Carolina
NC <- 97.6 + 88.6 + 97.7 + 92.8 + 99.2
NCcost <- NC/n
trueNC <- 95.7
cat("The average index in North Carolina is", NCcost, ", and the cost index is", trueNC, "\n")

# Pennsylvania
PA <-  107.8 + 98.0 + 109.7 + 105.6 + 102.9
PAcost <- PA/n
truePA <- 102.5
cat("The average index in Pennsylvania is", PAcost, ", and the cost index is", truePA, "\n")

# Texas
TX <- 90.8 + 83.8 + 103.2 + 94.1 + 97.0
TXcost <- TX/n
trueTX <- 92.1
cat("The average index in Texas is", TXcost, ", and the cost index is", trueTX, "\n")

# Virginia
VA <- 95.2 + 111.5 + 96.7 + 90.4 + 100.2
VAcost <- VA/n
trueVA <- 101.8
cat("The average index in Illinois is", VAcost, ", and the cost index is", trueVA, "\n")

# Washington
WA <- 108.4 + 119.0 + 90.8 + 117.4+ 110.4
WAcost <- WA/n
trueWA <- 111.6
cat("The average index in Washington is", WAcost, ", and the cost index is", trueWA)
```




```{r, ref.label=knitr::all_labels(), echo = TRUE, eval = FALSE}
```